PedAnimations = {
    {label = 'None', dict = '', anim = '', flag = 0},
    {label = 'Hands Up', dict = 'missminuteman_1ig_2', anim = 'handsup_base', flag = 49},
    {label = 'Drunk', dict = 'move_m@drunk@verydrunk', anim = 'fidget_07', flag = 49},
    {label = 'Smoking', dict = 'amb@world_human_smoking@male@male_a@base', anim = 'base', flag = 49},
    {label = 'Clipboard', dict = 'missfam4', anim = 'base', flag = 49},
    {label = 'Lean Against Wall', dict = 'amb@world_human_leaning@male@wall@back@foot_up@idle_a', anim = 'idle_a', flag = 49},
    {label = 'Sit On Ground', dict = 'amb@world_human_picnic@male@idle_a', anim = 'idle_a', flag = 1},
    {label = 'Sit In Chair', dict = 'amb@world_human_stupor@male@idle_a', anim = 'idle_a', flag = 1},
    {label = 'Phone Call', dict = 'cellphone@', anim = 'cellphone_call_listen_base', flag = 49},
    {label = 'Taking Photos', dict = 'amb@world_human_tourist_mobile@male@base', anim = 'base', flag = 49},
    {label = 'Yoga', dict = 'amb@world_human_yoga@male@base', anim = 'base_a', flag = 1},
    {label = 'Fishing', dict = 'amb@world_human_stand_fishing@base', anim = 'base', flag = 1},
    {label = 'Cop Standby', dict = 'amb@world_human_cop_idles@male@base', anim = 'base', flag = 49},
    {label = 'Medic Tending', dict = 'amb@medic@standing@tendtodead@base', anim = 'base', flag = 1},
    {label = 'Binoculars', dict = 'amb@world_human_binoculars@male@base', anim = 'base', flag = 49},
    {label = 'Welding', dict = 'amb@world_human_welding@male@base', anim = 'base', flag = 1},
    {label = 'Wash', dict = 'amb@world_human_maid_clean@', anim = 'base', flag = 1},
    {label = 'Kneel', dict = 'amb@world_human_gardener_plant@male@base', anim = 'base', flag = 1},
    {label = 'Guard', dict = 'amb@world_human_guard_patrol@male@base', anim = 'base', flag = 49},
    {label = 'Hammering', dict = 'amb@world_human_hammering@male@base', anim = 'base', flag = 1},
    {label = 'Cheering', dict = 'amb@world_human_cheering@male_a', anim = 'base', flag = 1},
    {label = 'Dancing', dict = 'anim@mp_player_intcelebrationfemale@wave', anim = 'wave', flag = 49},
    {label = 'Push Ups', dict = 'amb@world_human_push_ups@male@base', anim = 'base', flag = 1},
    {label = 'Sit Ups', dict = 'amb@world_human_sit_ups@male@base', anim = 'base', flag = 1},
    {label = 'Sunbathe', dict = 'amb@world_human_sunbathe@male@back@base', anim = 'base', flag = 1},
    {label = 'Sunbathe 2', dict = 'amb@world_human_sunbathe@male@front@base', anim = 'base', flag = 1},
    {label = 'Prostitute', dict = 'mini@prostitutes@sexlow_veh', anim = 'low_car_sex_loop_player', flag = 1},
    {label = 'Cower', dict = 'amb@code_human_cower@male@base', anim = 'base', flag = 1},
    {label = 'Cry', dict = 'mp_suicide', anim = 'pistol', flag = 1},
    {label = 'Facepalm', dict = 'anim@mp_player_intcelebrationmale@face_palm', anim = 'face_palm', flag = 49},
    {label = 'Finger Kiss', dict = 'anim@mp_player_intcelebrationmale@finger_kiss', anim = 'finger_kiss', flag = 49},
    {label = 'Finger Point', dict = 'anim@mp_player_intcelebrationmale@finger_point', anim = 'finger_point', flag = 49},
    {label = 'Handshake', dict = 'mp_common', anim = 'givetake1_a', flag = 49},
    {label = 'Jog', dict = 'move_m@jog@', anim = 'idle', flag = 49},
    {label = 'Kneel Hurt', dict = 'amb@medic@standing@kneel@base', anim = 'base', flag = 1},
    {label = 'Knock Door', dict = 'timetable@jimmy@doorknock@', anim = 'knockdoor_idle', flag = 49},
    {label = 'Laugh', dict = 'anim@mp_player_intcelebrationmale@laugh', anim = 'laugh', flag = 49},
    {label = 'Lean Bar', dict = 'amb@prop_human_bum_shopping_cart@male@base', anim = 'base', flag = 49},
    {label = 'Lean Rail', dict = 'amb@world_human_leaning@female@rail@base', anim = 'base', flag = 49},
    {label = 'Lookout', dict = 'amb@world_human_binoculars@male@base', anim = 'base', flag = 49},
    {label = 'Medic Kneel', dict = 'amb@medic@standing@kneel@base', anim = 'base', flag = 1},
    {label = 'Medic Tending 2', dict = 'amb@medic@standing@tendtodead@idle_a', anim = 'idle_a', flag = 1},
    {label = 'Muscle Flex', dict = 'amb@world_human_muscle_flex@arms_at_side@base', anim = 'base', flag = 1},
    {label = 'Notepad', dict = 'amb@world_human_clipboard@male@base', anim = 'base', flag = 49},
    {label = 'Parking Meter', dict = 'amb@world_human_parking_meter@male@base', anim = 'base', flag = 49},
    {label = 'Party', dict = 'amb@world_human_partying@female@base', anim = 'base', flag = 49},
    {label = 'Point', dict = 'gestures@f@standing@casual', anim = 'gesture_point', flag = 49},
    {label = 'Push', dict = 'missfinale_c2ig_11', anim = 'pushcar_offcliff_f', flag = 1},
    {label = 'Salute', dict = 'anim@mp_player_intcelebrationmale@salute', anim = 'salute', flag = 49},
    {label = 'Scratch Head', dict = 'anim@mp_player_intcelebrationmale@scratch_head', anim = 'scratch_head', flag = 49},
    {label = 'Shake Head', dict = 'anim@mp_player_intcelebrationmale@thumbs_up', anim = 'thumbs_up', flag = 49},
    {label = 'Shocked', dict = 'anim@mp_player_intcelebrationmale@shocked', anim = 'shocked', flag = 49},
    {label = 'Shower', dict = 'amb@world_human_bum_wash@male@high@base', anim = 'base', flag = 1},
    {label = 'Sit Chair', dict = 'amb@world_human_stupor@male@idle_a', anim = 'idle_a', flag = 1},
    {label = 'Sit Chair 2', dict = 'amb@world_human_stupor@male@idle_b', anim = 'idle_b', flag = 1},
    {label = 'Sit Chair 3', dict = 'amb@world_human_stupor@male@idle_c', anim = 'idle_c', flag = 1},
    {label = 'Sit Chair 4', dict = 'amb@world_human_stupor@male@idle_d', anim = 'idle_d', flag = 1},
    {label = 'Sit Chair 5', dict = 'amb@world_human_stupor@male@idle_e', anim = 'idle_e', flag = 1},
    {label = 'Sit Chair 6', dict = 'amb@world_human_stupor@male@idle_f', anim = 'idle_f', flag = 1},
    {label = 'Sit Chair 7', dict = 'amb@world_human_stupor@male@idle_g', anim = 'idle_g', flag = 1},
    {label = 'Sit Chair 8', dict = 'amb@world_human_stupor@male@idle_h', anim = 'idle_h', flag = 1},
    {label = 'Sit Chair 9', dict = 'amb@world_human_stupor@male@idle_i', anim = 'idle_i', flag = 1},
    {label = 'Sit Chair 10', dict = 'amb@world_human_stupor@male@idle_j', anim = 'idle_j', flag = 1},
    {label = 'Sit Chair 11', dict = 'amb@world_human_stupor@male@idle_k', anim = 'idle_k', flag = 1},
    {label = 'Sit Chair 12', dict = 'amb@world_human_stupor@male@idle_l', anim = 'idle_l', flag = 1},
    {label = 'Sit Chair 13', dict = 'amb@world_human_stupor@male@idle_m', anim = 'idle_m', flag = 1},
    {label = 'Sit Chair 14', dict = 'amb@world_human_stupor@male@idle_n', anim = 'idle_n', flag = 1},
    {label = 'Sit Chair 15', dict = 'amb@world_human_stupor@male@idle_o', anim = 'idle_o', flag = 1},
    {label = 'Sit Chair 16', dict = 'amb@world_human_stupor@male@idle_p', anim = 'idle_p', flag = 1},
    {label = 'Sit Chair 17', dict = 'amb@world_human_stupor@male@idle_q', anim = 'idle_q', flag = 1},
    {label = 'Sit Chair 18', dict = 'amb@world_human_stupor@male@idle_r', anim = 'idle_r', flag = 1},
    {label = 'Sit Chair 19', dict = 'amb@world_human_stupor@male@idle_s', anim = 'idle_s', flag = 1},
    {label = 'Sit Chair 20', dict = 'amb@world_human_stupor@male@idle_t', anim = 'idle_t', flag = 1},
    {label = 'Sit Chair 21', dict = 'amb@world_human_stupor@male@idle_u', anim = 'idle_u', flag = 1},
    {label = 'Sit Chair 22', dict = 'amb@world_human_stupor@male@idle_v', anim = 'idle_v', flag = 1},
    {label = 'Sit Chair 23', dict = 'amb@world_human_stupor@male@idle_w', anim = 'idle_w', flag = 1},
    {label = 'Sit Chair 24', dict = 'amb@world_human_stupor@male@idle_x', anim = 'idle_x', flag = 1},
    {label = 'Sit Chair 25', dict = 'amb@world_human_stupor@male@idle_y', anim = 'idle_y', flag = 1},
    {label = 'Sit Chair 26', dict = 'amb@world_human_stupor@male@idle_z', anim = 'idle_z', flag = 1},
    {label = 'Sit Chair 27', dict = 'amb@world_human_stupor@male@idle_aa', anim = 'idle_aa', flag = 1},
    {label = 'Sit Chair 28', dict = 'amb@world_human_stupor@male@idle_ab', anim = 'idle_ab', flag = 1},
    {label = 'Sit Chair 29', dict = 'amb@world_human_stupor@male@idle_ac', anim = 'idle_ac', flag = 1},
    {label = 'Sit Chair 30', dict = 'amb@world_human_stupor@male@idle_ad', anim = 'idle_ad', flag = 1},
    {label = 'Sit Chair 31', dict = 'amb@world_human_stupor@male@idle_ae', anim = 'idle_ae', flag = 1},
    {label = 'Sit Chair 32', dict = 'amb@world_human_stupor@male@idle_af', anim = 'idle_af', flag = 1},
    {label = 'Sit Chair 33', dict = 'amb@world_human_stupor@male@idle_ag', anim = 'idle_ag', flag = 1},
    {label = 'Sit Chair 34', dict = 'amb@world_human_stupor@male@idle_ah', anim = 'idle_ah', flag = 1},
    {label = 'Sit Chair 35', dict = 'amb@world_human_stupor@male@idle_ai', anim = 'idle_ai', flag = 1},
    {label = 'Sit Chair 36', dict = 'amb@world_human_stupor@male@idle_aj', anim = 'idle_aj', flag = 1},
    {label = 'Sit Chair 37', dict = 'amb@world_human_stupor@male@idle_ak', anim = 'idle_ak', flag = 1},
    {label = 'Sit Chair 38', dict = 'amb@world_human_stupor@male@idle_al', anim = 'idle_al', flag = 1},
    {label = 'Sit Chair 39', dict = 'amb@world_human_stupor@male@idle_am', anim = 'idle_am', flag = 1},
    {label = 'Sit Chair 40', dict = 'amb@world_human_stupor@male@idle_an', anim = 'idle_an', flag = 1},
    {label = 'Sit Chair 41', dict = 'amb@world_human_stupor@male@idle_ao', anim = 'idle_ao', flag = 1},
    {label = 'Sit Chair 42', dict = 'amb@world_human_stupor@male@idle_ap', anim = 'idle_ap', flag = 1},
    {label = 'Sit Chair 43', dict = 'amb@world_human_stupor@male@idle_aq', anim = 'idle_aq', flag = 1},
    {label = 'Sit Chair 44', dict = 'amb@world_human_stupor@male@idle_ar', anim = 'idle_ar', flag = 1},
    {label = 'Sit Chair 45', dict = 'amb@world_human_stupor@male@idle_as', anim = 'idle_as', flag = 1},
    {label = 'Sit Chair 46', dict = 'amb@world_human_stupor@male@idle_at', anim = 'idle_at', flag = 1},
    {label = 'Sit Chair 47', dict = 'amb@world_human_stupor@male@idle_au', anim = 'idle_au', flag = 1},
    {label = 'Sit Chair 48', dict = 'amb@world_human_stupor@male@idle_av', anim = 'idle_av', flag = 1},
    {label = 'Sit Chair 49', dict = 'amb@world_human_stupor@male@idle_aw', anim = 'idle_aw', flag = 1},
    {label = 'Sit Chair 50', dict = 'amb@world_human_stupor@male@idle_ax', anim = 'idle_ax', flag = 1},
    {label = 'Sit Chair 51', dict = 'amb@world_human_stupor@male@idle_ay', anim = 'idle_ay', flag = 1},
    {label = 'Sit Chair 52', dict = 'amb@world_human_stupor@male@idle_az', anim = 'idle_az', flag = 1},
    {label = 'Sit Chair 53', dict = 'amb@world_human_stupor@male@idle_ba', anim = 'idle_ba', flag = 1},
    {label = 'Sit Chair 54', dict = 'amb@world_human_stupor@male@idle_bb', anim = 'idle_bb', flag = 1},
    {label = 'Sit Chair 55', dict = 'amb@world_human_stupor@male@idle_bc', anim = 'idle_bc', flag = 1},
    {label = 'Sit Chair 56', dict = 'amb@world_human_stupor@male@idle_bd', anim = 'idle_bd', flag = 1},
    {label = 'Sit Chair 57', dict = 'amb@world_human_stupor@male@idle_be', anim = 'idle_be', flag = 1},
    {label = 'Sit Chair 58', dict = 'amb@world_human_stupor@male@idle_bf', anim = 'idle_bf', flag = 1},
    {label = 'Sit Chair 59', dict = 'amb@world_human_stupor@male@idle_bg', anim = 'idle_bg', flag = 1},
    {label = 'Sit Chair 60', dict = 'amb@world_human_stupor@male@idle_bh', anim = 'idle_bh', flag = 1},
    {label = 'Sit Chair 61', dict = 'amb@world_human_stupor@male@idle_bi', anim = 'idle_bi', flag = 1},
    {label = 'Sit Chair 62', dict = 'amb@world_human_stupor@male@idle_bj', anim = 'idle_bj', flag = 1},
    {label = 'Sit Chair 63', dict = 'amb@world_human_stupor@male@idle_bk', anim = 'idle_bk', flag = 1},
    {label = 'Sit Chair 64', dict = 'amb@world_human_stupor@male@idle_bl', anim = 'idle_bl', flag = 1},
    {label = 'Sit Chair 65', dict = 'amb@world_human_stupor@male@idle_bm', anim = 'idle_bm', flag = 1},
    {label = 'Sit Chair 66', dict = 'amb@world_human_stupor@male@idle_bn', anim = 'idle_bn', flag = 1},
    {label = 'Sit Chair 67', dict = 'amb@world_human_stupor@male@idle_bo', anim = 'idle_bo', flag = 1},
    {label = 'Sit Chair 68', dict = 'amb@world_human_stupor@male@idle_bp', anim = 'idle_bp', flag = 1},
    {label = 'Sit Chair 69', dict = 'amb@world_human_stupor@male@idle_bq', anim = 'idle_bq', flag = 1},
    {label = 'Sit Chair 70', dict = 'amb@world_human_stupor@male@idle_br', anim = 'idle_br', flag = 1},
    {label = 'Sit Chair 71', dict = 'amb@world_human_stupor@male@idle_bs', anim = 'idle_bs', flag = 1},
    {label = 'Sit Chair 72', dict = 'amb@world_human_stupor@male@idle_bt', anim = 'idle_bt', flag = 1},
    {label = 'Sit Chair 73', dict = 'amb@world_human_stupor@male@idle_bu', anim = 'idle_bu', flag = 1},
    {label = 'Sit Chair 74', dict = 'amb@world_human_stupor@male@idle_bv', anim = 'idle_bv', flag = 1},
    {label = 'Sit Chair 75', dict = 'amb@world_human_stupor@male@idle_bw', anim = 'idle_bw', flag = 1},
    {label = 'Sit Chair 76', dict = 'amb@world_human_stupor@male@idle_bx', anim = 'idle_bx', flag = 1},
    {label = 'Sit Chair 77', dict = 'amb@world_human_stupor@male@idle_by', anim = 'idle_by', flag = 1},
    {label = 'Sit Chair 78', dict = 'amb@world_human_stupor@male@idle_bz', anim = 'idle_bz', flag = 1},
    {label = 'Sit Chair 79', dict = 'amb@world_human_stupor@male@idle_ca', anim = 'idle_ca', flag = 1},
    {label = 'Sit Chair 80', dict = 'amb@world_human_stupor@male@idle_cb', anim = 'idle_cb', flag = 1},
    {label = 'Sit Chair 81', dict = 'amb@world_human_stupor@male@idle_cc', anim = 'idle_cc', flag = 1},
    {label = 'Sit Chair 82', dict = 'amb@world_human_stupor@male@idle_cd', anim = 'idle_cd', flag = 1},
    {label = 'Sit Chair 83', dict = 'amb@world_human_stupor@male@idle_ce', anim = 'idle_ce', flag = 1},
    {label = 'Sit Chair 84', dict = 'amb@world_human_stupor@male@idle_cf', anim = 'idle_cf', flag = 1},
    {label = 'Sit Chair 85', dict = 'amb@world_human_stupor@male@idle_cg', anim = 'idle_cg', flag = 1},
    {label = 'Sit Chair 86', dict = 'amb@world_human_stupor@male@idle_ch', anim = 'idle_ch', flag = 1},
    {label = 'Sit Chair 87', dict = 'amb@world_human_stupor@male@idle_ci', anim = 'idle_ci', flag = 1},
    {label = 'Sit Chair 88', dict = 'amb@world_human_stupor@male@idle_cj', anim = 'idle_cj', flag = 1},
    {label = 'Sit Chair 89', dict = 'amb@world_human_stupor@male@idle_ck', anim = 'idle_ck', flag = 1},
    {label = 'Sit Chair 90', dict = 'amb@world_human_stupor@male@idle_cl', anim = 'idle_cl', flag = 1},
    {label = 'Sit Chair 91', dict = 'amb@world_human_stupor@male@idle_cm', anim = 'idle_cm', flag = 1},
    {label = 'Sit Chair 92', dict = 'amb@world_human_stupor@male@idle_cn', anim = 'idle_cn', flag = 1},
    {label = 'Sit Chair 93', dict = 'amb@world_human_stupor@male@idle_co', anim = 'idle_co', flag = 1},
    {label = 'Sit Chair 94', dict = 'amb@world_human_stupor@male@idle_cp', anim = 'idle_cp', flag = 1},
    {label = 'Sit Chair 95', dict = 'amb@world_human_stupor@male@idle_cq', anim = 'idle_cq', flag = 1},
    {label = 'Sit Chair 96', dict = 'amb@world_human_stupor@male@idle_cr', anim = 'idle_cr', flag = 1},
    {label = 'Sit Chair 97', dict = 'amb@world_human_stupor@male@idle_cs', anim = 'idle_cs', flag = 1},
    {label = 'Sit Chair 98', dict = 'amb@world_human_stupor@male@idle_ct', anim = 'idle_ct', flag = 1},
    {label = 'Sit Chair 99', dict = 'amb@world_human_stupor@male@idle_cu', anim = 'idle_cu', flag = 1},
    {label = 'Sit Chair 100', dict = 'amb@world_human_stupor@male@idle_cv', anim = 'idle_cv', flag = 1}
}

function ApplyPedAnimation(ped, animIndex)
    if not animIndex or not PedAnimations[animIndex] then
        print("Invalid animation index:", animIndex)
        return
    end
    
    local anim = PedAnimations[animIndex]
    
    if anim.dict == '' or anim.anim == '' then
        return
    end
    
    if not HasAnimDictLoaded(anim.dict) then
        RequestAnimDict(anim.dict)
        
        local timeout = 500
        while not HasAnimDictLoaded(anim.dict) and timeout > 0 do
            Wait(10)
            timeout = timeout - 1
        end
        
        if timeout <= 0 then
            TriggerEvent('chat:addMessage', {
                color = {255, 0, 0},
                multiline = true,
                args = {"Error", "Failed to load animation"}
            })
            return
        end
    end
    
    TaskPlayAnim(ped, anim.dict, anim.anim, 8.0, -8.0, -1, anim.flag, 0, false, false, false)
end