PedModels = {
    {label = 'Beach Female', model = 'a_f_m_beach_01'},
    {label = 'Beverly Hills Female 1', model = 'a_f_m_bevhills_01'},
    {label = 'Beverly Hills Female 2', model = 'a_f_m_bevhills_02'},
    {label = 'Bodybuilder Female', model = 'a_f_m_bodybuild_01'},
    {label = 'Business Female', model = 'a_f_m_business_02'},
    {label = 'Downtown Female', model = 'a_f_m_downtown_01'},
    {label = 'East SA Female 1', model = 'a_f_m_eastsa_01'},
    {label = 'East SA Female 2', model = 'a_f_m_eastsa_02'},
    {label = 'Fat Black Female', model = 'a_f_m_fatbla_01'},
    {label = 'Fat Cult Female', model = 'a_f_m_fatcult_01'},
    {label = 'Fat White Female', model = 'a_f_m_fatwhite_01'},
    {label = 'Korean Female 1', model = 'a_f_m_ktown_01'},
    {label = 'Korean Female 2', model = 'a_f_m_ktown_02'},
    {label = 'Prologue Host Female', model = 'a_f_m_prolhost_01'},
    {label = 'Salton Female', model = 'a_f_m_salton_01'},
    {label = 'Skid Row Female', model = 'a_f_m_skidrow_01'},
    {label = 'South Central Female 1', model = 'a_f_m_soucent_01'},
    {label = 'South Central Female 2', model = 'a_f_m_soucent_02'},
    {label = 'South Central MC Female', model = 'a_f_m_soucentmc_01'},
    {label = 'Tourist Female', model = 'a_f_m_tourist_01'},
    {label = 'Tramp Female', model = 'a_f_m_tramp_01'},
    {label = 'Tramp Beach Female', model = 'a_f_m_trampbeac_01'},
    {label = 'Gen Street Female', model = 'a_f_o_genstreet_01'},
    {label = 'Indian Female', model = 'a_f_o_indian_01'},
    {label = 'Korean Old Female', model = 'a_f_o_ktown_01'},
    {label = 'Salton Old Female', model = 'a_f_o_salton_01'},
    {label = 'South Central Old Female 1', model = 'a_f_o_soucent_01'},
    {label = 'South Central Old Female 2', model = 'a_f_o_soucent_02'},
    {label = 'Beach Young Female', model = 'a_f_y_beach_01'},
    {label = 'Beverly Hills Young Female 1', model = 'a_f_y_bevhills_01'},
    {label = 'Beverly Hills Young Female 2', model = 'a_f_y_bevhills_02'},
    {label = 'Beverly Hills Young Female 3', model = 'a_f_y_bevhills_03'},
    {label = 'Beverly Hills Young Female 4', model = 'a_f_y_bevhills_04'},
    {label = 'Business Young Female 1', model = 'a_f_y_business_01'},
    {label = 'Business Young Female 2', model = 'a_f_y_business_02'},
    {label = 'Business Young Female 3', model = 'a_f_y_business_03'},
    {label = 'Business Young Female 4', model = 'a_f_y_business_04'},
    {label = 'Club Customer Female 1', model = 'a_f_y_clubcust_01'},
    {label = 'Club Customer Female 2', model = 'a_f_y_clubcust_02'},
    {label = 'Club Customer Female 3', model = 'a_f_y_clubcust_03'},
    {label = 'East SA Young Female 1', model = 'a_f_y_eastsa_01'},
    {label = 'East SA Young Female 2', model = 'a_f_y_eastsa_02'},
    {label = 'East SA Young Female 3', model = 'a_f_y_eastsa_03'},
    {label = 'Epsilon Young Female', model = 'a_f_y_epsilon_01'},
    {label = 'Female Agent', model = 'a_f_y_femaleagent'},
    {label = 'Fitness Young Female 1', model = 'a_f_y_fitness_01'},
    {label = 'Fitness Young Female 2', model = 'a_f_y_fitness_02'},
    {label = 'Gen Hot Young Female', model = 'a_f_y_genhot_01'},
    {label = 'Golfer Young Female', model = 'a_f_y_golfer_01'},
    {label = 'Hiker Young Female', model = 'a_f_y_hiker_01'},
    {label = 'Hippie Young Female', model = 'a_f_y_hippie_01'},
    {label = 'Hipster Young Female 1', model = 'a_f_y_hipster_01'},
    {label = 'Hipster Young Female 2', model = 'a_f_y_hipster_02'},
    {label = 'Hipster Young Female 3', model = 'a_f_y_hipster_03'},
    {label = 'Hipster Young Female 4', model = 'a_f_y_hipster_04'},
    {label = 'Indian Young Female', model = 'a_f_y_indian_01'},
    {label = 'Juggalo Young Female', model = 'a_f_y_juggalo_01'},
    {label = 'Runner Young Female', model = 'a_f_y_runner_01'},
    {label = 'Rural Meth Addict Young Female', model = 'a_f_y_rurmeth_01'},
    {label = 'SC Dressy Young Female', model = 'a_f_y_scdressy_01'},
    {label = 'Skater Young Female', model = 'a_f_y_skater_01'},
    {label = 'South Central Young Female 1', model = 'a_f_y_soucent_01'},
    {label = 'South Central Young Female 2', model = 'a_f_y_soucent_02'},
    {label = 'South Central Young Female 3', model = 'a_f_y_soucent_03'},
    {label = 'Tennis Young Female', model = 'a_f_y_tennis_01'},
    {label = 'Topless Young Female', model = 'a_f_y_topless_01'},
    {label = 'Tourist Young Female 1', model = 'a_f_y_tourist_01'},
    {label = 'Tourist Young Female 2', model = 'a_f_y_tourist_02'},
    {label = 'Vinewood Young Female 1', model = 'a_f_y_vinewood_01'},
    {label = 'Vinewood Young Female 2', model = 'a_f_y_vinewood_02'},
    {label = 'Vinewood Young Female 3', model = 'a_f_y_vinewood_03'},
    {label = 'Vinewood Young Female 4', model = 'a_f_y_vinewood_04'},
    {label = 'Yoga Young Female', model = 'a_f_y_yoga_01'},
    {label = 'Gen Casino Patron Young Female', model = 'a_f_y_gencaspat_01'},
    {label = 'Smart Casino Patron Young Female', model = 'a_f_y_smartcaspat_01'},
    {label = 'Beach Male', model = 'a_m_m_beach_01'},
    {label = 'Beach Male 2', model = 'a_m_m_beach_02'},
    {label = 'Beverly Hills Male 1', model = 'a_m_m_bevhills_01'},
    {label = 'Beverly Hills Male 2', model = 'a_m_m_bevhills_02'},
    {label = 'Business Male', model = 'a_m_m_business_01'},
    {label = 'East SA Male 1', model = 'a_m_m_eastsa_01'},
    {label = 'East SA Male 2', model = 'a_m_m_eastsa_02'},
    {label = 'Farmer Male', model = 'a_m_m_farmer_01'},
    {label = 'Fat Latino Male', model = 'a_m_m_fatlatin_01'},
    {label = 'Gen Fat Male 1', model = 'a_m_m_genfat_01'},
    {label = 'Gen Fat Male 2', model = 'a_m_m_genfat_02'},
    {label = 'Golfer Male', model = 'a_m_m_golfer_01'},
    {label = 'Hasidic Jew Male', model = 'a_m_m_hasjew_01'},
    {label = 'Hillbilly Male 1', model = 'a_m_m_hillbilly_01'},
    {label = 'Hillbilly Male 2', model = 'a_m_m_hillbilly_02'},
    {label = 'Indian Male', model = 'a_m_m_indian_01'},
    {label = 'Korean Male 1', model = 'a_m_m_ktown_01'},
    {label = 'Malibu Male', model = 'a_m_m_malibu_01'},
    {label = 'Mexican Country Male', model = 'a_m_m_mexcntry_01'},
    {label = 'Mexican Laborer Male', model = 'a_m_m_mexlabor_01'},
    {label = 'OG Boss Male', model = 'a_m_m_og_boss_01'},
    {label = 'Paparazzi Male', model = 'a_m_m_paparazzi_01'},
    {label = 'Polynesian Male', model = 'a_m_m_polynesian_01'},
    {label = 'Prologue Host Male', model = 'a_m_m_prolhost_01'},
    {label = 'Rural Meth Addict Male', model = 'a_m_m_rurmeth_01'},
    {label = 'Salton Male 1', model = 'a_m_m_salton_01'},
    {label = 'Salton Male 2', model = 'a_m_m_salton_02'},
    {label = 'Salton Male 3', model = 'a_m_m_salton_03'},
    {label = 'Salton Male 4', model = 'a_m_m_salton_04'},
    {label = 'Skater Male', model = 'a_m_m_skater_01'},
    {label = 'Skid Row Male', model = 'a_m_m_skidrow_01'},
    {label = 'South Central Latino Male', model = 'a_m_m_socenlat_01'},
    {label = 'South Central Male 1', model = 'a_m_m_soucent_01'},
    {label = 'South Central Male 2', model = 'a_m_m_soucent_02'},
    {label = 'South Central Male 3', model = 'a_m_m_soucent_03'},
    {label = 'South Central Male 4', model = 'a_m_m_soucent_04'},
    {label = 'Street Latino Male', model = 'a_m_m_stlat_02'},
    {label = 'Tennis Male', model = 'a_m_m_tennis_01'},
    {label = 'Tourist Male', model = 'a_m_m_tourist_01'},
    {label = 'Tramp Male', model = 'a_m_m_tramp_01'},
    {label = 'Tramp Beach Male', model = 'a_m_m_trampbeac_01'},
    {label = 'Transvestite Male 1', model = 'a_m_m_tranvest_01'},
    {label = 'Transvestite Male 2', model = 'a_m_m_tranvest_02'},
    {label = 'Acult Male Old', model = 'a_m_o_acult_01'},
    {label = 'Acult Male Old 2', model = 'a_m_o_acult_02'},
    {label = 'Beach Old Male', model = 'a_m_o_beach_01'},
    {label = 'Gen Street Old Male', model = 'a_m_o_genstreet_01'},
    {label = 'Korean Old Male', model = 'a_m_o_ktown_01'},
    {label = 'Salton Old Male', model = 'a_m_o_salton_01'},
    {label = 'South Central Old Male 1', model = 'a_m_o_soucent_01'},
    {label = 'South Central Old Male 2', model = 'a_m_o_soucent_02'},
    {label = 'South Central Old Male 3', model = 'a_m_o_soucent_03'},
    {label = 'Tramp Old Male', model = 'a_m_o_tramp_01'},
    {label = 'Acult Male Young', model = 'a_m_y_acult_01'},
    {label = 'Acult Male Young 2', model = 'a_m_y_acult_02'},
    {label = 'Beach Young Male 1', model = 'a_m_y_beach_01'},
    {label = 'Beach Young Male 2', model = 'a_m_y_beach_02'},
    {label = 'Beach Young Male 3', model = 'a_m_y_beach_03'},
    {label = 'Beach Vespucci Young Male 1', model = 'a_m_y_beachvesp_01'},
    {label = 'Beach Vespucci Young Male 2', model = 'a_m_y_beachvesp_02'},
    {label = 'Beverly Hills Young Male 1', model = 'a_m_y_bevhills_01'},
    {label = 'Beverly Hills Young Male 2', model = 'a_m_y_bevhills_02'},
    {label = 'Breakdance Young Male', model = 'a_m_y_breakdance_01'},
    {label = 'Busboy Young Male', model = 'a_m_y_busicas_01'},
    {label = 'Business Young Male 1', model = 'a_m_y_business_01'},
    {label = 'Business Young Male 2', model = 'a_m_y_business_02'},
    {label = 'Business Young Male 3', model = 'a_m_y_business_03'},
    {label = 'Club Customer Young Male 1', model = 'a_m_y_clubcust_01'},
    {label = 'Club Customer Young Male 2', model = 'a_m_y_clubcust_02'},
    {label = 'Club Customer Young Male 3', model = 'a_m_y_clubcust_03'},
    {label = 'Cyclist Young Male', model = 'a_m_y_cyclist_01'},
    {label = 'DHill Young Male', model = 'a_m_y_dhill_01'},
    {label = 'Downtown Young Male', model = 'a_m_y_downtown_01'},
    {label = 'East SA Young Male 1', model = 'a_m_y_eastsa_01'},
    {label = 'East SA Young Male 2', model = 'a_m_y_eastsa_02'},
    {label = 'Epsilon Young Male 1', model = 'a_m_y_epsilon_01'},
    {label = 'Epsilon Young Male 2', model = 'a_m_y_epsilon_02'},
    {label = 'Gay Young Male 1', model = 'a_m_y_gay_01'},
    {label = 'Gay Young Male 2', model = 'a_m_y_gay_02'},
    {label = 'Gen Street Young Male 1', model = 'a_m_y_genstreet_01'},
    {label = 'Gen Street Young Male 2', model = 'a_m_y_genstreet_02'},
    {label = 'Golfer Young Male', model = 'a_m_y_golfer_01'},
    {label = 'Hasidic Jew Young Male', model = 'a_m_y_hasjew_01'},
    {label = 'Hiker Young Male', model = 'a_m_y_hiker_01'},
    {label = 'Hippie Young Male', model = 'a_m_y_hippy_01'},
    {label = 'Hipster Young Male 1', model = 'a_m_y_hipster_01'},
    {label = 'Hipster Young Male 2', model = 'a_m_y_hipster_02'},
    {label = 'Hipster Young Male 3', model = 'a_m_y_hipster_03'},
    {label = 'Indian Young Male', model = 'a_m_y_indian_01'},
    {label = 'Jetski Young Male', model = 'a_m_y_jetski_01'},
    {label = 'Juggalo Young Male', model = 'a_m_y_juggalo_01'},
    {label = 'Korean Young Male 1', model = 'a_m_y_ktown_01'},
    {label = 'Korean Young Male 2', model = 'a_m_y_ktown_02'},
    {label = 'Latino Young Male', model = 'a_m_y_latino_01'},
    {label = 'Methhead Young Male', model = 'a_m_y_methhead_01'},
    {label = 'Mexican Thug Young Male', model = 'a_m_y_mexthug_01'},
    {label = 'Motox Young Male 1', model = 'a_m_y_motox_01'},
    {label = 'Motox Young Male 2', model = 'a_m_y_motox_02'},
    {label = 'Muscle Beach Young Male 1', model = 'a_m_y_musclbeac_01'},
    {label = 'Muscle Beach Young Male 2', model = 'a_m_y_musclbeac_02'},
    {label = 'Polynesian Young Male', model = 'a_m_y_polynesian_01'},
    {label = 'Road Cyclist Young Male', model = 'a_m_y_roadcyc_01'},
    {label = 'Runner Young Male 1', model = 'a_m_y_runner_01'},
    {label = 'Runner Young Male 2', model = 'a_m_y_runner_02'},
    {label = 'Salton Young Male', model = 'a_m_y_salton_01'},
    {label = 'Skater Young Male 1', model = 'a_m_y_skater_01'},
    {label = 'Skater Young Male 2', model = 'a_m_y_skater_02'},
    {label = 'South Central Young Male 1', model = 'a_m_y_soucent_01'},
    {label = 'South Central Young Male 2', model = 'a_m_y_soucent_02'},
    {label = 'South Central Young Male 3', model = 'a_m_y_soucent_03'},
    {label = 'South Central Young Male 4', model = 'a_m_y_soucent_04'},
    {label = 'St. Blaise Young Male 1', model = 'a_m_y_stbla_01'},
    {label = 'St. Blaise Young Male 2', model = 'a_m_y_stbla_02'},
    {label = 'Street Latino Young Male', model = 'a_m_y_stlat_01'},
    {label = 'Street White Young Male 1', model = 'a_m_y_stwhi_01'},
    {label = 'Street White Young Male 2', model = 'a_m_y_stwhi_02'},
    {label = 'Sunbather Young Male', model = 'a_m_y_sunbathe_01'},
    {label = 'Surfer Young Male', model = 'a_m_y_surfer_01'},
    {label = 'Vinewood Douche Young Male', model = 'a_m_y_vindouche_01'},
    {label = 'Vinewood Young Male 1', model = 'a_m_y_vinewood_01'},
    {label = 'Vinewood Young Male 2', model = 'a_m_y_vinewood_02'},
    {label = 'Vinewood Young Male 3', model = 'a_m_y_vinewood_03'},
    {label = 'Vinewood Young Male 4', model = 'a_m_y_vinewood_04'},
    {label = 'Yoga Young Male', model = 'a_m_y_yoga_01'},
    {label = 'Gen Casino Patron Young Male', model = 'a_m_y_gencaspat_01'},
    {label = 'Smart Casino Patron Young Male', model = 'a_m_y_smartcaspat_01'}
}

function LoadModel(model)
    if not IsModelInCdimage(model) then
        TriggerEvent('chat:addMessage', {
            color = {255, 0, 0},
            multiline = true,
            args = {"Error", "Model not found in game files"}
        })
        return false
    end
    
    RequestModel(model)
    
    local timeout = 500
    while not HasModelLoaded(model) and timeout > 0 do
        Wait(10)
        timeout = timeout - 1
    end
    
    if timeout <= 0 then
        TriggerEvent('chat:addMessage', {
            color = {255, 0, 0},
            multiline = true,
            args = {"Error", "Failed to load model in time"}
        })
        return false
    end
    
    return true
end

function GetModelNameFromHash(hash)
    local modelName = "Unknown"
    
    for _, pedInfo in ipairs(PedModels) do
        if GetHashKey(pedInfo.model) == hash then
            modelName = pedInfo.label
            break
        end
    end
    
    return modelName
end